### PR TITLE
Remove leading zeros in tag to make tag consistent with PyPI release

### LINKED ISSUE #17: Tags are inconsistent with PyPI versions
`v0.2023.07.31.00.32.45` in https://github.com/astropy/astropy-iers-data/tags is released as `0.2023.7.31.0.32.45` on https://pypi.org/project/astropy-iers-data/#history . Kinda confusing.

### PR DESCRIPTION
**Pull request by astrofrog**
Fixes https://github.com/astropy/astropy-iers-data/issues/17

### CODE REVIEW

**Comment by astrofrog** [comment]
CI failure unrelated, fixed in #29

**Comment by pllim** [comment]
I merged #29. Please rebase. Thanks!

**Comment by pllim** [comment]
No one (especially `astropy`) is relying on the leading zeroes in some sort of pattern grepping, right?

**Comment by astrofrog** [comment]
I doubt it since the release on PyPI don't have the leading zeros. It's only the tags here.

**Comment by astrofrog** [comment]
Rebased

**Comment by astrofrog** [comment]
I'll merge and try it out

**Pull request merged**
