### PR TITLE
Remove ReadMe.eopc04_IAU2000 file

### PR DESCRIPTION
**Pull request by astrofrog**
@mhvk @taldcroft - I was wondering whether perhaps we should actually not include this file here, it is mainly a backward-compatibility relic that shouldn't ever need updating so I'm not sure it actually needs to be included in this new package? We can just keep it in astropy/utils/iers/data and everything will continue to work as before?

### CODE REVIEW

**Review by pllim — APPROVED** [review]
I like as little breakage as possible.

**Review by taldcroft — APPROVED** [review]
Excellent idea.

**Comment by taldcroft** [comment]
If this is merged then I assume there will be a follow-on to https://github.com/astropy/astropy/pull/14819 to put the file back into astropy core?

**Comment by astrofrog** [comment]
Yes indeed I will update the astropy core PR

**Pull request merged**
