### PR TITLE
Replace broken leap seconds mirror URL

### PR DESCRIPTION
**Pull request by pllim**
I cannot tell if astropy would need a new way to parse this or not. I hope @mhvk or @astrofrog can advise here. See https://github.com/astropy/astropy/issues/15416

### CODE REVIEW

**Comment by astrofrog** [comment]
Maybe we should have a way to run the tests using just the mirrors - will think about it

**Comment by pllim** [comment]
I *think* that this PR would work as-is in astropy, at least to the extend that it is tested in https://github.com/astropy/astropy/actions/runs/6395885649/job/17360516265?pr=15420 over at https://github.com/astropy/astropy/pull/15420 (the pre-release daily cron job).

**Comment by mhvk** [comment]
Gee, @pllim, how did you even figure out where the file was moved to? The IETF website is super unhelpful!

**Comment by pllim** [comment]
I asked a couple of contacts I happen to have. 😅

**Comment by pllim** [comment]
FWIW this same patch is already applied directly in astropy for v5.3.x and v5.0.x. This one would only affect main (v6.0.x).

**Review by mhvk — APPROVED** [review]
Since we know this worked, I'm A-OK with it!

**Comment by pllim** [comment]
@mhvk , I only know the CI does not fail, but I have no idea how much this mirror thing is tested in the CI. So some manual confirmation that it actually works as intended would be nice.

@astrofrog , when can we release a new `astropy-iers-data` or do I have to wait for the auto release?

**Comment by mhvk** [comment]
CI does read the file, so I think it should be fine.  It also looks identical in format to the old one.

**Pull request merged**
